[package]
name = "binary_boarding"
version = "0.1.0"
authors = ["Robin Valk <robin.valk@merapar.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
